# Generated by Django 6.0.4 on 2026-04-22 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel_name",
                    models.CharField(max_length=100, verbose_name="название канала"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="дата")),
                ("program_id", models.IntegerField(verbose_name="id программы")),
                ("duration", models.IntegerField(verbose_name="длительность")),
                ("title", models.CharField(max_length=100, verbose_name="название")),
                ("description", models.TextField(verbose_name="описание")),
                ("age_rating", models.IntegerField(verbose_name="возрастной рейтинг")),
                (
                    "sub_title",
                    models.CharField(
                        max_length=200, null=True, verbose_name="серия, название серии"
                    ),
                ),
                ("category", models.TextField(verbose_name="категории")),
                ("start_time", models.DateTimeField(verbose_name="время начала")),
                (
                    "channel_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="autogen.channel",
                        verbose_name="название канала",
                    ),
                ),
            ],
        ),
    ]
