# Generated by Django 6.0.4 on 2026-04-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autogen", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="premier",
            field=models.BooleanField(null=True, verbose_name="премьера"),
        ),
        migrations.AddField(
            model_name="program",
            name="priority",
            field=models.FloatField(default=0.0, verbose_name="приоритет программы"),
        ),
        migrations.AlterField(
            model_name="program",
            name="description",
            field=models.TextField(null=True, verbose_name="описание"),
        ),
    ]
