# Generated by Django 6.0.4 on 2026-04-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autogen", "0002_program_premier_program_priority_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="program_id",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="id программы"
            ),
        ),
    ]
