# Generated by Django 6.0.4 on 2026-04-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autogen", "0003_alter_program_program_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="sub_title",
            field=models.CharField(
                max_length=400, null=True, verbose_name="серия, название серии"
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="title",
            field=models.CharField(max_length=400, verbose_name="название"),
        ),
    ]
